const translations = {
  de: {
    title: "Mein Pokédex",
    searchPlaceholder: "Name, ID oder Typ",
    loadButton: "Lade Pokémon",
    detailHeight: "Größe",
    detailWeight: "Gewicht",
    detailExperience: "Basiserfahrung",
    detailAbilities: "Fähigkeiten",
  },
  en: {
    title: "My Pokédex",
    searchPlaceholder: "Name, ID or Type",
    loadButton: "Load Pokémon",
    detailHeight: "Height",
    detailWeight: "Weight",
    detailExperience: "Base esperience",
    detailAbilities: "Abilities",
  },
  fr: {
    title: "Mon Pokédex",
    searchPlaceholder: "Nom, ID ou Type",
    loadButton: "Charger Pokémon",
    detailHeight: "Taille",
    detailWeight: "Poids",
    detailExperience: "Expérience de base",
    detailAbilities: "Capacités",
  },
  es: {
    title: "Mi Pokédex",
    searchPlaceholder: "Nombre, ID o Tipo",
    loadButton: "Cargar Pokémon",
    detailHeight: "Altura",
    detailWeight: "Peso",
    detailExperience: "Experiencia base",
    detailAbilities: "Habilidades",
  },
};
